export { renderMethod, identityEdits, identitySchemaEdits } from "./schema";
export type {
  SchemaEdits,
  Edits,
  DereffedOpenrpcDocument,
  DereffedMethodObject,
  DereffedMethodObjectParams,
  NoRefs,
} from "./type";

import {
  dereferenceDocument,
  parseOpenRPCDocument,
} from "@open-rpc/schema-utils-js";
import type {
  DereffedMethodObject,
  DereffedOpenrpcDocument,
  Edits,
  NoRefs,
  SchemaEdits,
} from "./type";
import { identitySchemaEdits, renderMethod } from "./schema";
import { toMarkdown } from "mdast-util-to-markdown";
import { gfmToMarkdown } from "mdast-util-gfm";
import { mdxToMarkdown } from "mdast-util-mdx";
import { frontmatterToMarkdown } from "mdast-util-frontmatter";
export type { OpenRPCMdContent } from "./type";

import type { Root } from "mdast";
import type { MethodObject, OpenrpcDocument } from "@open-rpc/meta-schema";
import fs from "fs/promises";
import path from "path";

interface MethodToMarkdown {
  methodName: string;
  markdown: string;
}

function escapeYaml(str: string): string {
  return str.replace(/"/g, '\\"').replace(/\n/g, " ");
}

function postProcessMarkdown(markdown: string): string {
  return markdown;
}

export async function renderMethodsToMarkdown(
  document: OpenrpcDocument,
  edits: Edits,
  schemaEdits: SchemaEdits = identitySchemaEdits,
): Promise<MethodToMarkdown[]> {
  // TODO: figure this one out

  const dereferencedDocument = await dereferenceDocument(document);
  const parsedDocument = await parseOpenRPCDocument(dereferencedDocument);

  return parsedDocument.methods.map((method) => {
    const methodContent = renderMethod(
      method as NoRefs<MethodObject>,
      schemaEdits,
      edits,
    );
    const rootDocument: Root = {
      type: "root",
      children: methodContent,
    };
    return {
      methodName: (method as DereffedMethodObject).name,
      markdown: postProcessMarkdown(
        toMarkdown(rootDocument, {
          extensions: [
            gfmToMarkdown(),
            mdxToMarkdown(),
            frontmatterToMarkdown(),
          ],
        }),
      ),
    };
  });
}

export async function renderDocumentToMarkdownFiles(
  methodsDir: string,
  document: OpenrpcDocument,
  edits: Edits,
  _schemaEdits: SchemaEdits,
  markdownType: "mdx" | "md",
): Promise<void> {
  const methods = await renderMethodsToMarkdown(document, edits, _schemaEdits);
  await Promise.all(
    methods.map(async (method) => {
      fs.writeFile(
        path.join(methodsDir, `${method.methodName}.${markdownType}`),
        method.markdown,
      );
    }),
  );
  // write an index.md file
  await fs.writeFile(
    path.join(methodsDir, "index.md"),
    renderIndex(document as DereffedOpenrpcDocument, markdownType),
    "utf8",
  );
}

export function renderIndex(
  doc: DereffedOpenrpcDocument,
  markdownType: "mdx" | "md",
): string {
  const title = doc.info?.title || "API";
  const version = doc.info?.version || "";
  const desc = doc.info?.description || "";
  const methods = doc.methods || [];
  const schemas = Object.keys(doc.components?.schemas || {});

  const tags = methods
    .flatMap((m) => m.tags?.map((t) => t?.name) || [])
    .filter(Boolean);
  const uniqueTags = [...new Set(tags)];
  const tagsList =
    uniqueTags.length === 0
      ? ""
      : `tags:\n${uniqueTags.map((t) => `  - "${t}"`).join("\n")}`;

  const methodsList =
    methods.length === 0
      ? "_No methods defined._"
      : methods
          .map((m) => `- [\`${m.name}\`](./methods/${m.name}.${markdownType})`)
          .join("\n");

  // eslint-disable-next-line @typescript-eslint/no-unused-vars
  const _schemasList =
    schemas.length === 0
      ? "_No schemas defined._"
      : schemas
          .map(
            (s) => `- [\`${s}\`](./schemas/${s.toLowerCase()}.${markdownType})`,
          )
          .join("\n");

  return `---
# GENERATED DOCUMENTATION - DO NOT EDIT THIS FILE
title: "${title}"
description: "${escapeYaml(desc)}"
${tagsList}
---

# ${title}

${version ? `Version: \`${version}\`\n` : ""}${desc ? `\n${desc}\n` : ""}

## Methods

${methodsList}
`;
}
