import type { Content, PhrasingContent, RootContent } from "mdast";

export type JsonSchemaPrimitiveType =
  | "string"
  | "number"
  | "integer"
  | "boolean"
  | "null";

export type JsonSchemaComplexType = "object" | "array";

export type JsonSchemaType = JsonSchemaPrimitiveType | JsonSchemaComplexType;

export interface JsonSchema {
  type?: JsonSchemaType | JsonSchemaType[];
  title?: string;
  description?: string;
  format?: string;
  properties?: Record<string, JsonSchema>;
  required?: string[];
  items?: JsonSchema | JsonSchema[];
  additionalProperties?: boolean | JsonSchema;
  minProperties?: number;
  maxProperties?: number;
  dependentRequired?: Record<string, string[]>;
  minItems?: number;
  maxItems?: number;
  uniqueItems?: boolean;
  contains?: JsonSchema;
  minContains?: number;
  maxContains?: number;
  enum?: Array<string | number | boolean | null>;
  const?: unknown;
  default?: unknown;
  examples?: unknown[];
  pattern?: string;
  minLength?: number;
  maxLength?: number;
  exclusiveMinimum?: number;
  exclusiveMaximum?: number;
  minimum?: number;
  maximum?: number;
  multipleOf?: number;
}

export interface SchemaRenderContext {
  /**
   * The logical name of the schema, used when presenting inline summaries.
   */
  name: string;
}

export interface SchemaRenderResult {
  inline: PhrasingContent[];
  blocks: RootContent[];
}

export interface TypeRenderResult {
  /**
   * Additional phrasing content to append to the base summary.
   */
  summarySuffix?: PhrasingContent[];
  /**
   * Extra block-level content generated by the type-specific renderer.
   */
  blocks?: RootContent[];
}

export interface SchemaRendererHelpers {
  getResult(path: string): SchemaRenderResult | undefined;
  getContext(path: string): SchemaRenderContext | undefined;
}
